export const PERSONAL_PLANS = [
  {
    id: "free",
    name: "Free",
    price: "0",
    subtitle: "See what Serani AI can do",
    isCurrent: true,
    cta: "Start Free",
    features: [
      { icon: "sparkle", text: "Get simple emotional insights" },
      { icon: "chat", text: "Short AI chats for common questions" },
      { icon: "sparkle", text: "Basic journaling and mood tracking" },
      { icon: "shield", text: "Standard privacy & security" },
    ],
  },
  {
    id: "go",
    name: "Go",
    price: "5",
    subtitle: "Keep progressing with expanded access",
    cta: "Upgrade to Go",
    features: [
      { icon: "sparkle", text: "Explore topics in depth with AI" },
      { icon: "chat", text: "Chat longer and more frequently" },
      { icon: "sparkle", text: "More guided reflections & prompts" },
      { icon: "shield", text: "Improved account management" },
      { icon: "sparkle", text: "Extra token allowance monthly" },
    ],
  },
  {
    id: "plus",
    name: "Plus",
    price: "20",
    subtitle: "Unlock the full experience",
    badge: "POPULAR",
    highlight: true,
    cta: "Upgrade to Plus",
    features: [
      { icon: "sparkle", text: "Advanced AI insights & mood analysis" },
      { icon: "chat", text: "Multi-session chat memory support" },
      { icon: "sparkle", text: "Higher token limits (AI usage)" },
      { icon: "sparkle", text: "Premium reflective activities & courses" },
      { icon: "shield", text: "Enhanced privacy controls" },
      { icon: "sparkle", text: "Priority feature access" },
    ],
  },
  {
    id: "pro",
    name: "Pro",
    price: "40",
    subtitle: "Maximize productivity & growth",
    cta: "Upgrade to Pro",
    features: [
      { icon: "sparkle", text: "Maximum AI usage + best insights" },
      { icon: "chat", text: "Faster responses & priority handling" },
      { icon: "sparkle", text: "Deep analytics (mood + tasks)" },
      { icon: "sparkle", text: "Full access to all content & courses" },
      { icon: "shield", text: "Premium support channel" },
      { icon: "sparkle", text: "Best for heavy usage users" },
    ],
  },
];

export const BUSINESS_PLANS = [
  {
    id: "free_business",
    name: "Free",
    price: "0",
    subtitle: "Try Serani AI for teams (limited)",
    isCurrent: true,
    cta: "Start Free",
    features: [
      { icon: "sparkle", text: "Limited seats for testing" },
      { icon: "chat", text: "Limited AI usage per seat" },
      { icon: "shield", text: "Basic admin controls" },
      { icon: "sparkle", text: "Simple usage view" },
    ],
  },
  {
    id: "business",
    name: "Business",
    price: "30",
    subtitle: "Get more work done with Serani AI for teams",
    badge: "RECOMMENDED",
    highlight: true,
    cta: "Upgrade to Business",
    features: [
      { icon: "shield", text: "Organization dashboard + roles" },
      { icon: "sparkle", text: "Team usage analytics & insights" },
      { icon: "chat", text: "Higher AI usage per seat" },
      { icon: "shield", text: "SSO-ready (future)" },
      { icon: "sparkle", text: "Central billing + invoices" },
      { icon: "sparkle", text: "Bulk invites and onboarding" },
      { icon: "shield", text: "Admin controls for licenses" },
    ],
  },
];
