const DEFAULT_TASK_LIBRARY = [
  {
    taskId: "thought-reframing-1",
    title: "Thought Reframing Sprint",
    category: "Emotional Awareness",
    duration: "4 min",
    type: "input",
    isActive: true,
    difficulty: "medium",
    config: {
      prompt: "Write one negative thought, then rewrite it as a kinder and more realistic thought.",
      buttonLabel: "Save reframe",
      placeholder: "Original thought... then reframed thought...",
    },
  },
  {
    taskId: "distraction-blocker-1",
    title: "Distraction Blocker",
    category: "Focus",
    duration: "6 min",
    type: "timer",
    isActive: true,
    difficulty: "hard",
    config: {
      minutes: 6,
      instruction: "Keep one tab, one task, and one intention. No app switching until timer ends.",
    },
  },
  {
    taskId: "sound-awareness-1",
    title: "Sound Awareness Scan",
    category: "Mindfulness",
    duration: "3 min",
    type: "guided",
    isActive: true,
    difficulty: "easy",
    config: {
      steps: [
        "Pause and soften your shoulders.",
        "Name three sounds you can hear close to you.",
        "Name two sounds farther away.",
        "Take one slow breath and return to the room.",
      ],
    },
  },
  {
    taskId: "posture-reset-1",
    title: "Posture Reset",
    category: "Self-Care",
    duration: "2 min",
    type: "action",
    isActive: true,
    difficulty: "easy",
    config: {
      minutes: 2,
      instruction: "Sit tall, release jaw tension, roll shoulders back and down, then breathe for 5 cycles.",
    },
  },
  {
    taskId: "energy-boost-1",
    title: "Energy Boost Micro-Move",
    category: "Self-Care",
    duration: "5 min",
    type: "action",
    isActive: true,
    difficulty: "medium",
    config: {
      minutes: 5,
      instruction: "Stand up, stretch your arms overhead, do 20 light steps, then drink water.",
    },
  },
  {
    taskId: "perspective-shift-1",
    title: "Perspective Shift",
    category: "Emotional Awareness",
    duration: "4 min",
    type: "guided",
    isActive: true,
    difficulty: "medium",
    config: {
      steps: [
        "Think of one stressor right now.",
        "Imagine advising a close friend with the same stressor.",
        "Write one sentence of advice to that friend.",
        "Apply the same sentence to yourself.",
      ],
    },
  },
  {
    taskId: "emotion-to-action-1",
    title: "Emotion to Action",
    category: "Emotional Awareness",
    duration: "3 min",
    type: "input",
    isActive: true,
    difficulty: "easy",
    config: {
      prompt: "Name your current emotion, then choose one tiny action that supports that emotion.",
      buttonLabel: "Commit action",
      placeholder: "Emotion: ... | Action: ...",
    },
  },
  {
    taskId: "mental-reset-30",
    title: "30-Second Mental Reset",
    category: "Stress Relief",
    duration: "0.5 min",
    type: "breathing",
    isActive: true,
    difficulty: "easy",
    config: {
      cycles: 2,
      inhale: 4,
      hold: 2,
      exhale: 4,
      holdAfterExhale: 2,
    },
  },
];

module.exports = DEFAULT_TASK_LIBRARY;
